apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeview
  labels:
    app.kubernetes.io/name: kubeview
    app.kubernetes.io/instance: skale-safe-release
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeview
      app.kubernetes.io/instance: skale-safe-release
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeview
        app.kubernetes.io/instance: skale-safe-release
    spec:
      serviceAccountName: kubeview
      containers:
        - name: kubeview
          image: ghcr.io/benc-uk/kubeview: 0.1.31
          imagePullPolicy: always
          env:
            - name: IN_CLUSTER
              value: "true"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector: {}
      affinity: {}
      tolerations: []
